name: Build Azure Sphere Application

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'AzureSphere/MySphere/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Azure Sphere Apps
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image for azsphere builds and Start container from build image
      run: |
        docker build --build-arg FUNCTION_CONNECTION_STRING=${{ secrets.MY_CONNECTION_STRING }} --target build -t hlbuildimage -f AzureSphere/MySphere/Dockerfile .
        docker run --name hlbuildcontainer hlbuildimage
    - name: Copy container build output
      run:
        docker cp hlbuildcontainer:/out HLOutput
    - name: Publish imagepackage
      uses: actions/upload-artifact@v2
      with:
        name: HL imagepackage
        path: ${{ github.workspace }}/HLOutput/AvnetStarterKitReferenceDesign.imagepackage
