name: Build Azure Sphere Application

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'AzureSphere/MySphere/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Azure Sphere Apps
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image for azsphere builds and Start container from build image
      env: # Or as an environment variable
        MY_CONNECTION_STRING: ${{ secrets.MY_CONNECTION_STRING }}
      run: |
        docker build --build-arg MY_CONNECTION_STRING=gaga --target build -t hlbuildimage -f AzureSphere/MySphere/Dockerfile .
        docker run --name hlbuildcontainer hlbuildimage
    - name: Copy container build output
      run:
        docker cp hlbuildcontainer:/out HLOutput
    - name: Copy container build output
      run:
        docker cp hlbuildcontainer:/src HLOutput2        
    - name: Publish HL imagepackage
      uses: actions/upload-artifact@v2
      with:
        name: HL imagepackage
        path: ${{ github.workspace }}/HLOutput/AvnetStarterKitReferenceDesign.imagepackage
    - name: Publish HL imagepackage
      uses: actions/upload-artifact@v2
      with:
        name: HL file
        path: ${{ github.workspace }}/HLOutput2/*
